/* eslint-disable no-console */
import { showLogger } from '@/constant/env';

/**
 * A logger function that will only logs on development
 * @param object - The object to log
 * @param comment - Autogenerated with `lg` snippet
 * @param error - display error log
 */
export default function logger(object: unknown, comment?: string, error?:{error:boolean}): void {
  if (!showLogger) return;

  if(error){
    console.log(
      '%c 🛑 Error log: \n',
      'color: #FF2400',
      `page:  ${typeof window !== 'undefined' && window?.location.pathname}\n`,
      `event: ${comment ?? ''}\n`,
      object
    );
    return
  }

  console.log(
    '%c ℹ️ Info log: \n',
    'color: #22D3EE',
    `page:  ${typeof window !== 'undefined' && window?.location.pathname}\n`,
    `event: ${comment ?? ''}\n`,
    object
  );
}
